"""
SingleGroqLLM — single-model Groq wrapper with exponential-backoff retry.

Used for evaluation (answer generation and reflection) where cross-cell
comparability is load-bearing: every cell in the experiment matrix must be
generated by the same model so that score differences attribute to retrieval
mode and graph layer, not to model substitution.


On 429 / rate-limit:
  - Reads `try again in Xs` from the error message when present and waits X+0.5s.
  - Otherwise falls back to exponential backoff: 60s → 120s → 240s → 480s → 960s.
  - max_retries=5 by default. After exhausting retries, raises the original error.

No model substitution. No silent fallback. Every retry stays on the same model.
"""

import os
import re
import time
from typing import ClassVar
from dotenv import load_dotenv
from llama_index.llms.groq import Groq

load_dotenv()


class SingleGroqLLM(Groq):
    """
    Single-model Groq wrapper. Subclasses Groq so isinstance(self, LLM) passes.
    """

    DEFAULT_MODEL: ClassVar[str] = "llama-3.3-70b-versatile"
    DEFAULT_MAX_RETRIES: ClassVar[int] = 5
    BACKOFF_SCHEDULE: ClassVar[tuple] = (60.0, 120.0, 240.0, 480.0, 960.0)

    def __init__(self, model: str = None, max_retries: int = None, temperature: float = 0.0):
        api_key = os.getenv("GROQ_API_KEY")
        chosen_model = model or self.DEFAULT_MODEL
        # Initialise parent so isinstance(self, LLM) passes for LlamaIndex.
        # max_retries=0 disables LlamaIndex's tenacity wrapper so 429s reach our handler.
        super().__init__(
            model=chosen_model,
            api_key=api_key,
            temperature=temperature,
            max_retries=0,
        )
        # Hold an inner Groq instance to dispatch through — mirrors FallbackGroqLLM's
        # pattern and avoids any super() / self method resolution surprises.
        self._inner = Groq(
            model=chosen_model,
            api_key=api_key,
            temperature=temperature,
            max_retries=0,
        )
        self._sg_model_name = chosen_model
        self._sg_max_retries = max_retries if max_retries is not None else self.DEFAULT_MAX_RETRIES

    @staticmethod
    def _is_rate_limited(exc: Exception) -> bool:
        msg = str(exc).lower()
        return any(x in msg for x in ["429", "rate limit", "quota", "tokens per", "exhausted"])

    @staticmethod
    def _retry_after(exc: Exception) -> float | None:
        m = re.search(r"try again in\s+([\d.]+)s", str(exc), re.IGNORECASE)
        return float(m.group(1)) + 0.5 if m else None

    def _call_with_retry(self, method_name: str, *args, **kwargs):
        attempt = 0
        while True:
            try:
                return getattr(self._inner, method_name)(*args, **kwargs)
            except Exception as exc:
                if not self._is_rate_limited(exc):
                    raise
                if attempt >= self._sg_max_retries:
                    print(f"[{self._sg_model_name}] retries exhausted ({attempt}). Raising.")
                    raise
                hint = self._retry_after(exc)
                wait = hint if hint is not None else self.BACKOFF_SCHEDULE[
                    min(attempt, len(self.BACKOFF_SCHEDULE) - 1)
                ]
                attempt += 1
                print(
                    f"[{self._sg_model_name}] rate-limited "
                    f"(attempt {attempt}/{self._sg_max_retries}) -- "
                    f"waiting {wait:.1f}s then retrying same model..."
                )
                time.sleep(wait)

    def chat(self, messages, **kwargs):
        return self._call_with_retry("chat", messages, **kwargs)

    def complete(self, prompt, **kwargs):
        return self._call_with_retry("complete", prompt, **kwargs)

    def stream_chat(self, messages, **kwargs):
        return self._call_with_retry("stream_chat", messages, **kwargs)

    def stream_complete(self, prompt, **kwargs):
        return self._call_with_retry("stream_complete", prompt, **kwargs)
